version: '2.0'

services:

  rtl433:
    image: rtl433_weewx:latest
    #build: .
    tty: true
    container_name: rtl433_weewx
    #restart: always
    # need this to access the usb properly
    privileged: true
    devices:
      # you need to either allow access to all usb devices
      ##- /dev/bus/usb:/dev/bus/usb
      # or select them directly
      - /dev/bus/usb/005/002:/dev/bus/usb/005/002
  
    volumes:
      - ./shared/:/tmp/shared/
      # upload our config
      - ./weewx.conf:/etc/weewx/weewx.conf:ro
      # upload the updated sdr parser config
      - ./sdr.py:/usr/share/weewx/user/sdr.py
