version: '2.4'

services:

  rtl433:
    image: rtl433_weewx:latest
    #build: .
    tty: true
    container_name: rtl433_weewx
    # restart always = if unhealthy re-start the container
    restart: always
    # need this to access the usb properly
    privileged: true
    devices:
      # you need to either allow access to all usb devices
      ##- /dev/bus/usb:/dev/bus/usb
      # or select them directly
      - /dev/bus/usb/005/002:/dev/bus/usb/005/002
  
    volumes:
      - ./shared/:/tmp/shared/
      # upload our config
      - ./weewx.conf:/etc/weewx/weewx.conf:ro
      # upload the updated sdr parser config
      - ./sdr.py:/usr/share/weewx/user/sdr.py

    # check health here:   docker inspect --format='{{json .State.Health}}' rtl433_weewx | jq .
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/usr/local/bin/healthcheck.sh",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      # delay long enough for weewx to gather an update and send to WU 
      start_period: 3m
